// Generated by https://Quicktype.in

import { IColumn } from "./IPasteles";

export interface ICategoria {
    id:          string;
    name:        string;
    descripcion: string;
    logo:        string;
}

const ColumCategoria:IColumn[] = [
    {
        key: "name",
        label: "Nombre",
      },
      {
        key: "descripcion",
        label: "Titulo",
      },
      {
        key: "logo",
        label: "Imagen",
      },
];

export default ColumCategoria;
